FROM  jcxldn/openjdk-alpine:15-jdk
RUN apk update && \
    apk upgrade -U && \
    apk add ca-certificates ffmpeg libwebp libwebp-tools && \
    rm -rf /var/cache/*
RUN mkdir -p /app/
ADD /build/libs/api-adm-luxore-1.0.jar /app/api-adm-luxore-1.0.jar
RUN mkdir -p /keys/
ADD src/main/resources/credentials.json /tokens/credentials.json
ENV GOOGLE_APPLICATION_CREDENTIALS /tokens/credentials.json
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/api-adm-luxore-1.0.jar"]