server:
  port: 8080
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://34.44.19.26:3306/luxore
    username: root
    password: lUx20230849
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: false
name: luxore-prod
environment: production
enabled: true
servers:
  - luxore.mx
logging:
  level:
    org:
      springframework:
        web: DEBUG
        boot:
          autoconfigure:
            security:
              servlet:
                UserDetailsServiceAutoConfiguration: OFF
    com:
      myapp:
        service: INFO
  file:
    name: logs/luxore.log
credentials:
  path: /credentials.json