server:
  port: 8080
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/luxore
    username: root
    password: MY$QL2023
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      # ddl-auto: create    create tables from entity java
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: false
name: luxore-test
environment: testing
enabled: false
servers:
  - luxore.mx
  - localhost
logging:
  level:
    org:
      springframework:
        web: DEBUG
        boot:
          autoconfigure:
            security:
              servlet:
                UserDetailsServiceAutoConfiguration: OFF
    com:
      myapp:
        service: INFO
  file:
    name: logs/luxore.log
credentials:
  path: /credentials.json
